/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo;

//String nombre, int id, int edad, String [] trabajo, String genero, String gradoEscolaridad) //

import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.ListModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author josue
 */
public class Inicio extends javax.swing.JFrame {
    public Login login;
    public Familia familiaActual;
    public MetodoFamilia familias;
    public CrearUsuario creaUsuario = new CrearUsuario();
    public AnadeTrabajo anadeTrabajo = new AnadeTrabajo();

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        jComboTipoTrans.setEnabled(false);
        tabInfo.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                jTextTransacciones.setText("");
                jTextReportes.setText("");
                DefaultListModel listModel = new DefaultListModel();
                listModel.addElement("");
                jListados.setModel(listModel);
                jTextInfoFam.setText("");
            }
        });
        ((DefaultEditor) jSpinSemana.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor) jSpinnerSemana.getEditor()).getTextField().setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tabInfo = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnCrearUsuario = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextInfoFam = new javax.swing.JTextArea();
        btnMiembros = new javax.swing.JButton();
        btnEgresosFam = new javax.swing.JButton();
        btnIngresosFam = new javax.swing.JButton();
        btnAhorrosFam = new javax.swing.JButton();
        btnClaseSocial = new javax.swing.JButton();
        btnNuevoTrabajo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnPorcentajes = new javax.swing.JButton();
        btnAhorros = new javax.swing.JButton();
        btnGastosBasicos = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextReportes = new javax.swing.JTextArea();
        btnAutorrealizacion = new javax.swing.JButton();
        btnEscolarAhorro = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListados = new javax.swing.JList<>();
        btnFamiliasIngreso = new javax.swing.JButton();
        btnFamiliasSinAhorro = new javax.swing.JButton();
        btnFamiliasAhorro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAnadirTransaccion = new javax.swing.JButton();
        jComboTransaccion = new javax.swing.JComboBox<>();
        jComboTipoTrans = new javax.swing.JComboBox<>();
        jTextDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIngresos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboElegirFam = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextMonto = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextTransacciones = new javax.swing.JTextArea();
        btnEgresos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSpinSemana = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jCombofamiliares = new javax.swing.JComboBox<>();
        Familiar = new javax.swing.JLabel();
        jSpinnerSemana = new javax.swing.JSpinner();
        Familiar1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextSemana = new javax.swing.JTextArea();
        btnIngresosSemana = new javax.swing.JButton();
        btnEgresosSemana = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton2.setText("Familia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jButton4.setText("jButton4");

        jButton3.setText("Familia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText("Estado");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descripcion", "Semana", "Comentario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("FAMILY");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel3.setText("BANK");

        btnCrearUsuario.setText("Crear nuevo familiar");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        jTextInfoFam.setEditable(false);
        jTextInfoFam.setColumns(20);
        jTextInfoFam.setRows(5);
        jScrollPane6.setViewportView(jTextInfoFam);

        btnMiembros.setText("Ver miembros de familia");
        btnMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiembrosActionPerformed(evt);
            }
        });

        btnEgresosFam.setText("Total de gastos familiares");
        btnEgresosFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgresosFamActionPerformed(evt);
            }
        });

        btnIngresosFam.setText("Total de ingresos familiares");
        btnIngresosFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosFamActionPerformed(evt);
            }
        });

        btnAhorrosFam.setText("Ahorros Familiares");
        btnAhorrosFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAhorrosFamActionPerformed(evt);
            }
        });

        btnClaseSocial.setText("Clase Social");
        btnClaseSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaseSocialActionPerformed(evt);
            }
        });

        btnNuevoTrabajo.setText("Añadir trabajo");
        btnNuevoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTrabajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMiembros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEgresosFam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIngresosFam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAhorrosFam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClaseSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoTrabajo)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnMiembros)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresosFam)
                        .addGap(18, 18, 18)
                        .addComponent(btnEgresosFam)
                        .addGap(18, 18, 18)
                        .addComponent(btnAhorrosFam)
                        .addGap(18, 18, 18)
                        .addComponent(btnClaseSocial))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearUsuario)
                    .addComponent(btnNuevoTrabajo))
                .addContainerGap())
        );

        tabInfo.addTab("Info Familia", jPanel1);

        btnPorcentajes.setText("Porcentaje clase sociales");
        btnPorcentajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajesActionPerformed(evt);
            }
        });

        btnAhorros.setText("Capacidad de ahorro");
        btnAhorros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAhorrosActionPerformed(evt);
            }
        });

        btnGastosBasicos.setText("Gastos basicos");
        btnGastosBasicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosBasicosActionPerformed(evt);
            }
        });

        jTextReportes.setEditable(false);
        jTextReportes.setColumns(20);
        jTextReportes.setRows(5);
        jScrollPane4.setViewportView(jTextReportes);

        btnAutorrealizacion.setText("Gastos en autorrealizacion");
        btnAutorrealizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorrealizacionActionPerformed(evt);
            }
        });

        btnEscolarAhorro.setText("Grado escolar mas ahorrativo");
        btnEscolarAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolarAhorroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnPorcentajes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGastosBasicos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAutorrealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEscolarAhorro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnPorcentajes)
                        .addGap(18, 18, 18)
                        .addComponent(btnAhorros)
                        .addGap(18, 18, 18)
                        .addComponent(btnGastosBasicos)
                        .addGap(18, 18, 18)
                        .addComponent(btnAutorrealizacion)
                        .addGap(18, 18, 18)
                        .addComponent(btnEscolarAhorro))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        tabInfo.addTab("Reportes", jPanel4);

        jScrollPane3.setViewportView(jListados);

        btnFamiliasIngreso.setText("Familias por ingreso descendente");
        btnFamiliasIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiliasIngresoActionPerformed(evt);
            }
        });

        btnFamiliasSinAhorro.setText("Familias sin ahorros");
        btnFamiliasSinAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiliasSinAhorroActionPerformed(evt);
            }
        });

        btnFamiliasAhorro.setText("Familias por ahorro descendente");
        btnFamiliasAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiliasAhorroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnFamiliasSinAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnFamiliasIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnFamiliasAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFamiliasIngreso)
                    .addComponent(btnFamiliasAhorro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFamiliasSinAhorro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabInfo.addTab("Listado", jPanel5);

        btnAnadirTransaccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnAnadirTransaccion.setText("Añadir");
        btnAnadirTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirTransaccionActionPerformed(evt);
            }
        });

        jComboTransaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Egreso" }));
        jComboTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTransaccionActionPerformed(evt);
            }
        });

        jComboTipoTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoTransActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Tipo de trasaccion:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de egreso:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Descripcion:");

        btnIngresos.setText("Ingresos");
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Elegir miembro:");

        jComboElegirFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboElegirFamActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Monto:");

        jTextMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextMontoKeyTyped(evt);
            }
        });

        jTextTransacciones.setEditable(false);
        jTextTransacciones.setColumns(20);
        jTextTransacciones.setRows(5);
        jScrollPane7.setViewportView(jTextTransacciones);

        btnEgresos.setText("Egresos");
        btnEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgresosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Semana:");

        jSpinSemana.setModel(new javax.swing.SpinnerNumberModel(1, 1, 53, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnadirTransaccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jComboTipoTrans, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboTransaccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextMonto)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jSpinSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextDescripcion))
                        .addGap(48, 48, 48)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboElegirFam, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnIngresos)
                                .addGap(18, 18, 18)
                                .addComponent(btnEgresos)))))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboElegirFam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addComponent(jComboTipoTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnadirTransaccion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresos)
                            .addComponent(btnEgresos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tabInfo.addTab("Transaccion", jPanel2);

        Familiar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Familiar.setText("Familiar:");

        jSpinnerSemana.setModel(new javax.swing.SpinnerNumberModel(1, 1, 53, 1));

        Familiar1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Familiar1.setText("Semana:");

        jTextSemana.setColumns(20);
        jTextSemana.setRows(5);
        jScrollPane8.setViewportView(jTextSemana);

        btnIngresosSemana.setText("Ingresos");
        btnIngresosSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosSemanaActionPerformed(evt);
            }
        });

        btnEgresosSemana.setText("Egresos");
        btnEgresosSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgresosSemanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnIngresosSemana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEgresosSemana))
                    .addComponent(Familiar)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCombofamiliares, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Familiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Familiar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCombofamiliares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Familiar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresosSemana)
                            .addComponent(btnEgresosSemana)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        tabInfo.addTab("Info Semanal", jPanel6);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSalir)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabInfo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(tabInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //InfoFamilia siguiente = new InfoFamilia();
        //siguiente.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        creaUsuario.inicio = this;
        creaUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void jComboTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTransaccionActionPerformed
        if(jComboTransaccion.getSelectedItem().toString().equals("Ingreso")){
            jComboTipoTrans.setEnabled(false);
            jComboTipoTrans.removeAllItems();
        }else if(jComboTransaccion.getSelectedItem().toString().equals("Egreso")){
            jComboTipoTrans.setEnabled(true);
            String egresos[] = {"Fisiologia", "Seguridad", "Afiliacion", "Reconocimiento", "Autorrealizacion"};
            DefaultComboBoxModel model = new DefaultComboBoxModel(egresos);
            jComboTipoTrans.setModel(model);
        }
    }//GEN-LAST:event_jComboTransaccionActionPerformed
    
    public void setMiembros(){
        if(familiaActual.getMiembrosFamilia() == null){
            jComboElegirFam.setEnabled(false);
        }else{
            jComboElegirFam.setEnabled(true);
            String[] miembros = new String[familiaActual.getMiembrosFamilia().size()]; 
            for(int i = 0; i < familiaActual.getMiembrosFamilia().size(); i++){
                miembros[i] = familiaActual.getMiembrosFamilia().get(i).getNombre();
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(miembros);
            jComboElegirFam.setModel(model);
        }  
    }
    
    
    public void setMiembrosSemanales(){
        if(familiaActual.getMiembrosFamilia() == null){
            jCombofamiliares.setEnabled(false);
        }else{
            jCombofamiliares.setEnabled(true);
            String[] miembros = new String[familiaActual.getMiembrosFamilia().size()]; 
            for(int i = 0; i < familiaActual.getMiembrosFamilia().size(); i++){
                miembros[i] = familiaActual.getMiembrosFamilia().get(i).getNombre();
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(miembros);
            jCombofamiliares.setModel(model);
        }  
    }
    private void btnAnadirTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirTransaccionActionPerformed
        String usuario = (String)jComboElegirFam.getSelectedItem();
        if(usuario != null){
            Persona persona =  familiaActual.buscarPersona(usuario);
            if(jComboTransaccion.getSelectedItem().toString().equals("Ingreso")){
                persona.anadirIngreso(Integer.parseInt(jTextMonto.getText()), jTextDescripcion.getText(), (int)jSpinSemana.getValue());
                System.out.println("Anadio un ingreso a " + usuario + " con un monto de " + jTextMonto.getText());
                jTextMonto.setText("");
                jTextDescripcion.setText("");
            }else if(jComboTransaccion.getSelectedItem().toString().equals("Egreso")){
                if(Integer.parseInt(jTextMonto.getText()) > (persona.getTotalIngresos() - persona.getTotalEgresos())){
                    JOptionPane.showMessageDialog(rootPane, "No puede registrar un monto mayor a sus ahorros.");
                }
                    
                persona.anadirEgreso((String)jComboTipoTrans.getSelectedItem(), 
                        Integer.parseInt(jTextMonto.getText()), jTextDescripcion.getText(), (int)jSpinSemana.getValue());
                System.out.println("Anadio un egreso a " + usuario + " con un monto de " + jTextMonto.getText());
                jTextMonto.setText("");
                jTextDescripcion.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "No hay usuarios disponibles.");
        }
        
    }//GEN-LAST:event_btnAnadirTransaccionActionPerformed

    private void jTextMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMontoKeyTyped
        char validar=evt.getKeyChar();
        
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
            jTextMonto.setText("");
        }
    }//GEN-LAST:event_jTextMontoKeyTyped

    private void jComboElegirFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboElegirFamActionPerformed
        /*String usuario = (String)jComboElegirFam.getSelectedItem();
        Persona persona = familiaActual.buscarPersona(usuario);
        String[] ingresos = new String[persona.getIngresos().size()+1];
        //ingresos[1] = "Ingresos:";
        for(int i = 0; i < persona.getIngresos().size(); i++){
            Ingreso ing = persona.getIngresos().get(i);
            ingresos[i] = ing.getDescripcion() + " - " + ing.getMonto();
                    //familiaActual.getMiembrosFamilia().get(i).getNombre();
            jTextTransacciones.append(ing.getDescripcion() + " - " + ing.getMonto() + "\n");
            }*/
        
       
    }//GEN-LAST:event_jComboElegirFamActionPerformed

    private void btnPorcentajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajesActionPerformed
         jTextReportes.setText("");
        if(familiaActual.getMiembrosFamilia().isEmpty()){
            jTextReportes.append("El calculo no se puede realizar \nya que la familia actual no \ntiene miembros.");
        }else{
        jTextReportes.append(familias.calculaClasificacion());
        }
    }//GEN-LAST:event_btnPorcentajesActionPerformed

    private void btnAhorrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAhorrosActionPerformed
        jTextReportes.setText("");
        if(familiaActual.getMiembrosFamilia().isEmpty()){
            jTextReportes.append("El calculo no se puede realizar \nya que la familia actual no \ntiene miembros.");
        }else{
            jTextReportes.append(familias.capacidadAhorro());
        }
    }//GEN-LAST:event_btnAhorrosActionPerformed

    private void btnGastosBasicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosBasicosActionPerformed
        jTextReportes.setText("");
        if(familiaActual.getMiembrosFamilia().isEmpty()){
            jTextReportes.append("El calculo no se puede realizar \nya que la familia actual no \ntiene miembros.");
        }else{
            jTextReportes.append(familias.egresosFisiologiaSeguridad());
        }
    }//GEN-LAST:event_btnGastosBasicosActionPerformed

    private void btnAutorrealizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorrealizacionActionPerformed
         jTextReportes.setText("");
        if(familiaActual.getMiembrosFamilia().isEmpty()){
            jTextReportes.append("El calculo no se puede realizar \nya que la familia actual no \ntiene miembros.");
        }else{
        jTextReportes.append(familias.ingresosAutorrealizacion());
        }
    }//GEN-LAST:event_btnAutorrealizacionActionPerformed

    private void btnEscolarAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolarAhorroActionPerformed
         jTextReportes.setText("");
        if(familiaActual.getMiembrosFamilia().isEmpty()){
            jTextReportes.append("El calculo no se puede realizar \nya que la familia actual no \ntiene miembros.");
        }else{
        jTextReportes.append(familias.ahorroPorEscolaridad());
        }
    }//GEN-LAST:event_btnEscolarAhorroActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        login.setVisible(true);
        this.familiaActual = null;
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFamiliasAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiliasAhorroActionPerformed
        ArrayList<Familia> arraylist = familias.ordenAhorros();
        DefaultListModel model = new DefaultListModel();    
        for(Familia f: arraylist){
            model.addElement(f.getApellidosFamilia() + " de " + f.getProvincia() + ", " + f.getCanton() +
                    " posee " + (f.getTotalIngresos() - f.getTotalEgresos()) + " en ahorros.");
        }
        jListados.setModel(model);                        
    }//GEN-LAST:event_btnFamiliasAhorroActionPerformed

    private void btnFamiliasIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiliasIngresoActionPerformed
        ArrayList<Familia> arraylist = familias.ordenIngresos();
        DefaultListModel model = new DefaultListModel();
        //model.addElement("Familia: \t\t");
        for(Familia f: arraylist){
            model.addElement(f.getApellidosFamilia() + " de " + f.getProvincia() + ", " + f.getCanton() +
                    ", posee " + f.getTotalIngresos() + " en ingresos.");
        }
        jListados.setModel(model);
    }//GEN-LAST:event_btnFamiliasIngresoActionPerformed

    private void btnFamiliasSinAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiliasSinAhorroActionPerformed
        ArrayList<Familia> arraylist = familias.ListarSinAhorros();
        DefaultListModel model = new DefaultListModel();
        for(Familia f: arraylist){
            if(f.getTotalIngresos() - f.getTotalEgresos() == 0){
                model.addElement(f.getApellidosFamilia() + " de " + f.getProvincia() + ", " + f.getCanton() +
                    " no posee ahorros. ");
            }     
        }
        if(model.isEmpty()){
            model.addElement("No hay familias sin ahorros.");
        }
        jListados.setModel(model);
    }//GEN-LAST:event_btnFamiliasSinAhorroActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        jTextTransacciones.setText("");
        String usuario = (String)jComboElegirFam.getSelectedItem();
        if(usuario != null){
            Persona persona = familiaActual.buscarPersona(usuario);
            if(persona != null){
                jTextTransacciones.setText("");
                if(persona.getIngresos().isEmpty()){
                    jTextTransacciones.append("Este usuario no tiene \ningresos registrados.");
                }else{
                    for(Ingreso i: persona.getIngresos()){
                        jTextTransacciones.append(i.getDescripcion() + " - " + i.getMonto() + "\n");
                    }  
                }
            }
        }else{
            jTextTransacciones.append("No se ha elegido \nun usuario.");
        }    
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgresosActionPerformed
        jTextTransacciones.setText("");
        String usuario = (String)jComboElegirFam.getSelectedItem();
        if(usuario != null){
            Persona persona = familiaActual.buscarPersona(usuario);
            if(persona != null){
                jTextTransacciones.setText("");
                if(persona.getEgresos().isEmpty()){
                    jTextTransacciones.append("Este usuario no tiene \negresos registrados.");
                }else{
                    for(Egreso e: persona.getEgresos()){
                        jTextTransacciones.append(e.getDescripcion() + " - " + e.getMonto() + "\n");
                    }
                }
            }
        }else{
            jTextTransacciones.append("No se ha elegido \nun usuario.");
        }
    }//GEN-LAST:event_btnEgresosActionPerformed

    private void btnMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiembrosActionPerformed
        jTextInfoFam.setText("");
        if(familiaActual.getMiembrosFamilia().isEmpty()){
            jTextInfoFam.setText("Esta familia no tiene miembros.");
        }else{
            jTextInfoFam.append("Nombre:\tEdad:\n");
            for(Persona p: familiaActual.getMiembrosFamilia()){
                jTextInfoFam.append(p.getNombre() + "\t" + p.getEdad() + "\n");
            } 
        }   
    }//GEN-LAST:event_btnMiembrosActionPerformed

    private void btnIngresosFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosFamActionPerformed
        jTextInfoFam.setText("");
        if(familiaActual.getTotalIngresos() == 0){
            jTextInfoFam.setText("Esta familia no tiene \ningresos registrados.");
        }else{
            jTextInfoFam.setText("Esta familia registra "
                    + familiaActual.getTotalIngresos() + " \ncolones en ingresos.");
        }
    }//GEN-LAST:event_btnIngresosFamActionPerformed

    private void btnEgresosFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgresosFamActionPerformed
        jTextInfoFam.setText("");
        if(familiaActual.getTotalEgresos() == 0){
            jTextInfoFam.setText("Esta familia no tiene \negresos registrados.");
        }else{
            jTextInfoFam.setText("Esta familia registra "
                    + familiaActual.getTotalEgresos() + " \ncolones en egresos.");
        }
    }//GEN-LAST:event_btnEgresosFamActionPerformed

    private void btnAhorrosFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAhorrosFamActionPerformed
        jTextInfoFam.setText("");
        if((familiaActual.getTotalIngresos() - familiaActual.getTotalEgresos()) == 0){
            jTextInfoFam.setText("Esta familia no tiene ahorros.");
        }else{
            jTextInfoFam.setText("Esta familia registra "
                    + (familiaActual.getTotalIngresos() - familiaActual.getTotalEgresos())
                    + " \ncolones en ahorros.");
        }
    }//GEN-LAST:event_btnAhorrosFamActionPerformed

    private void btnClaseSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaseSocialActionPerformed
        jTextInfoFam.setText("");
        if(familiaActual.getClaseSocial() == null || familiaActual.getClaseSocial() == ""){
            jTextInfoFam.setText("Esta familia no ha clasificado \nsu Clase Social todavia.");
        }else{
            jTextInfoFam.setText("La familia " + familiaActual.getApellidosFamilia() + " es clasificada \ncomo " 
                    + familiaActual.getClaseSocial());
        }
    }//GEN-LAST:event_btnClaseSocialActionPerformed

    private void btnNuevoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTrabajoActionPerformed
        anadeTrabajo.setVisible(true);
        anadeTrabajo.familiaActual = this.familiaActual;
        anadeTrabajo.setMiembros();
    }//GEN-LAST:event_btnNuevoTrabajoActionPerformed

    private void jComboTipoTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoTransActionPerformed

    private void btnIngresosSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosSemanaActionPerformed
       String usuario = (String)jCombofamiliares.getSelectedItem();
       jTextSemana.setText("");
       if(usuario != null){
            Persona persona =  familiaActual.buscarPersona(usuario);
            ArrayList<Ingreso> ingSemana = persona.ingresosPorSemana((int)jSpinnerSemana.getValue());
            if(ingSemana.isEmpty()){
                jTextSemana.setText("Esta persona no posee ingresos\nen esa semana.");
            }else{
                jTextSemana.append("Ingresos:\tMonto: \n");
                for(Ingreso i: ingSemana){
                    jTextSemana.append(i.getDescripcion()+ "\t" + i.getMonto() +"\n");
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "No hay usuarios disponibles.");
        }
    }//GEN-LAST:event_btnIngresosSemanaActionPerformed

    private void btnEgresosSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgresosSemanaActionPerformed
       String usuario = (String)jCombofamiliares.getSelectedItem();
       jTextSemana.setText("");
       if(usuario != null){
            Persona persona =  familiaActual.buscarPersona(usuario);
            ArrayList<Egreso> engSemana = persona.egresosPorSemana((int)jSpinnerSemana.getValue());
            if(engSemana.isEmpty()){
                jTextSemana.setText("Esta persona no posee egresos\nen esa semana.");
            }else{
                jTextSemana.append("Ingresos:\tMonto: \n");
                for(Egreso e: engSemana){
                    jTextSemana.append(e.getDescripcion()+ "\t" + e.getMonto() +"\n");
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "No hay usuarios disponibles.");
        }
    }//GEN-LAST:event_btnEgresosSemanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Familiar;
    private javax.swing.JLabel Familiar1;
    private javax.swing.JButton btnAhorros;
    private javax.swing.JButton btnAhorrosFam;
    private javax.swing.JButton btnAnadirTransaccion;
    private javax.swing.JButton btnAutorrealizacion;
    private javax.swing.JButton btnClaseSocial;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEgresos;
    private javax.swing.JButton btnEgresosFam;
    private javax.swing.JButton btnEgresosSemana;
    private javax.swing.JButton btnEscolarAhorro;
    private javax.swing.JButton btnFamiliasAhorro;
    private javax.swing.JButton btnFamiliasIngreso;
    private javax.swing.JButton btnFamiliasSinAhorro;
    private javax.swing.JButton btnGastosBasicos;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnIngresosFam;
    private javax.swing.JButton btnIngresosSemana;
    private javax.swing.JButton btnMiembros;
    private javax.swing.JButton btnNuevoTrabajo;
    private javax.swing.JButton btnPorcentajes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboElegirFam;
    private javax.swing.JComboBox<String> jComboTipoTrans;
    private javax.swing.JComboBox<String> jComboTransaccion;
    private javax.swing.JComboBox<String> jCombofamiliares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jListados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSpinner jSpinSemana;
    private javax.swing.JSpinner jSpinnerSemana;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextArea jTextInfoFam;
    private javax.swing.JTextField jTextMonto;
    private javax.swing.JTextArea jTextReportes;
    private javax.swing.JTextArea jTextSemana;
    private javax.swing.JTextArea jTextTransacciones;
    private javax.swing.JTabbedPane tabInfo;
    // End of variables declaration//GEN-END:variables
}
